### ISSUE TITLE
Login button alignment not intuitive

### ISSUE THREAD

**Issue by KaroKatze** [praykor/CSC-289-Coffee#2]
The login button would look better if it was centered directly below the login fields, or to the right. By doing a google search on login screens, you can see it is almost always centered or placed on the bottom-right (rarely to the left). If the login button is to the left, it's not intuitive because the user has to go out of their way to click the button. If, instead, it's directly below the login fields, the user doesn't have to travel as far. Here are a few possibilities: 

![solution1](https://cloud.githubusercontent.com/assets/26307071/23913107/48540000-08b8-11e7-8552-84595fc99419.png)

![solution2](https://cloud.githubusercontent.com/assets/26307071/23913112/4cf19014-08b8-11e7-8e74-e2d52e16bd7a.png)

![solution3](https://cloud.githubusercontent.com/assets/26307071/23913426/59bbd3a8-08b9-11e7-974b-2f942a27a9a5.png)

![solution4](https://cloud.githubusercontent.com/assets/26307071/23913459/7812f4bc-08b9-11e7-87c0-4919eb282d0d.png)

**Comment by kenshin9441** [comment]
Feel free to change it. I like the second one ;)

**Comment by KaroKatze** [comment]
I like the second one too. I will put it as that for now... we can change it later if needed.
