### ISSUE TITLE
POS Design Ideas

### ISSUE THREAD

**Issue by KaroKatze** [praykor/CSC-289-Coffee#3]
How do we want to design the POS GUI? 

There are many ways we could design it. Here are some examples...

Some of these are terrible by themselves.. but they might give us some ideas about types of buttons or functions we could add if we feel like it. 

Feel free to add more! 

![pos1](https://cloud.githubusercontent.com/assets/26307071/23927155/7f91c4d6-08ee-11e7-9ee8-1fa5eea977b7.jpg)
![pos2](https://cloud.githubusercontent.com/assets/26307071/23927158/81859826-08ee-11e7-982a-ad1290e6a465.png)
![pos3](https://cloud.githubusercontent.com/assets/26307071/23927160/83785b50-08ee-11e7-8f2a-ce604f59e1db.png)
![pos4](https://cloud.githubusercontent.com/assets/26307071/23927164/85f74c42-08ee-11e7-8585-903d73d9dccd.png)
![pos5](https://cloud.githubusercontent.com/assets/26307071/23927165/8765bbfe-08ee-11e7-89a6-c9d5cb8cbbc1.png)
![pos6](https://cloud.githubusercontent.com/assets/26307071/23927167/89073bb8-08ee-11e7-9060-f9ceaedcacc9.png)
![pos7](https://cloud.githubusercontent.com/assets/26307071/23927171/8b0bc082-08ee-11e7-84b2-1d9e9e85be3c.png)
![pos8](https://cloud.githubusercontent.com/assets/26307071/23927173/8cd4e826-08ee-11e7-9569-e009b9f28fa0.png)
![pos9](https://cloud.githubusercontent.com/assets/26307071/23927174/8edc6b8a-08ee-11e7-9578-21135b1ebe56.png)

**Comment by kenshin9441** [comment]
It's not an issue, and if anybody has any question(another issue topic), please go to Discord and discuss about it.
I can see only 3 people participate in Github, and not everyone notices this.
I have posted something in Discord and no one else responded.

**Comment by kenshin9441** [comment]
To answer your question, and I also mentioned this in my email.
Most POS GUI uses buttons to present their products and a table to handle order detail.
In my opinion, colors, font, style, of objects in GUI makes them look good or bad. 
First step to build our GUI is build an outline using default style first. Then we can decorate for it later.
And to use buttons to present products in menu, I think we need to customize class button a bit to store product information. (we have to create class object for each table anyway if we want to connect to DB)
