### ISSUE TITLE
password reset: Why set username.

### ISSUE THREAD

**Issue by praykor** [praykor/CSC-289-Coffee#4]
Why would we enter a username, if we already know their username. If its a password reset, it implies they know their username.

**Comment by kenshin9441** [comment]
Go to any website that has password reset feature, try it and you will know why, (ex: reddit)

**Comment by KaroKatze** [comment]
Are we not going to have a "forgot username" feature?

**Comment by kenshin9441** [comment]
@KaroKatze no, we don't let users do it if they cannot identify themselves. Properly some systems let you do that cause they have your email to verify your action, but most of them don't do it.

**Comment by KaroKatze** [comment]
Ok makes sense.
